commerce_shipping.commerce_package_type.*:
  type: config_entity
  label: 'Package type'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Label'
    weight:
      type: integer
      label: 'Weight'
    physical_dimensions:
      type: physical_dimension
      label: 'Physical Dimensions'
    physical_weight:
      type: physical_measurement
      label: 'Physical Weight'
